import { readFile, writeFile } from 'node:fs/promises';
const dossier = new URL('.', import.meta.url);
const exemple = JSON.parse(await readFile(new URL('cartes-telephone-requete.json', dossier), 'utf8'));
const commun = `DÉCOR ENTIÈREMENT FICTIF DU BANC T0 : e2e/donnees/campagne-de-demo.json et e2e/tabletteJoueursT0.spec.ts. Aucune sauvegarde réelle ni donnée personnelle de David. GM-OS T3, lot J2, nouvelle conversation pour cet écran uniquement. Téléphone 390×844, utilisable dès 360 px. Même grammaire que Direct/Inventaire/Cartes retenus comme référence visuelle, même DESIGN.md : fond #020617, surfaces #0f172a/#1e293b, texte #f8fafc, secondaire #898c95, cyan #06b6d4, danger #ef4444. Orbitron titres, Inter corps ≥14 px, JetBrains Mono chiffres, badges ≥11 px. Cibles ≥44×44 px, zoom autorisé, aucun bandeau ou barre latérale de bureau. En-tête compact GM-OS, Connecté, bouton unique Mode performance / Mode qualité ; horloge projetée et Dimanche 4 octobre 2026 ; seule tension publique Alerte de la station 3/8. Navigation fixe : Direct, Archives, PNJ, Lieux, Inventaire, Cartes sur deux rangées de trois ; Fiche, Notes, Messages, Quitter sur une rangée de quatre. Réserver sa hauteur : contenu défilant au-dessus, aucun texte/action caché derrière. Aucun nouveau filtre, recherche, compteur technique, matricule, pourcentage, fonction ou contenu de jeu. HTML fonctionnel avec simulations locales uniquement. Les captures T0 ont été lues localement et transcrites, pas jointes à l'API. `;
const contenus = {
  archives: `Écran Archives. Source HubArchives.tsx + HubClueViewer.tsx. Horloge 23:36:43. Titre Archives du Groupe ; Preuves et indices collectés lors de la campagne. ; compteur 2 Fragments Découverts. Deux cartes touchables sans image (icône document neutre), sans date de découverte car absente : Le café encore chaud / Le départ date de moins d'une heure. ; La signature unique / Tout le registre est signé « Hale », même les nuits où il dormait. Aucun autre indice. Toucher ouvre une surcouche scrollable avec titre, texte intégral, document neutre, Archives Sécurisées / Preuve immatérielle ; bouton Fermer l'indice, toucher du fond ferme. Pas d'action Modifier, Partager, Favori. Onglet Archives actif. État vide réel : Aucune archive disponible. Ne pas inventer d'illustration.`,
  pnj: `Écran PNJ. Source HubTrombinoscope.tsx + HubNpcViewer.tsx. Horloge 23:36:50. Titre Trombinoscope ; Registre des individus et entités identifiés. ; compteur 1 Profils Répertoriés. Un seul profil touchable Superviseur Hale, rôle neutral, avatar absent : silhouette neutre. Aucun autre personnage. Toucher ouvre une surcouche scrollable : Identité Non Documentée, rôle neutral, nom complet Superviseur Hale, Profil Civil / Neutre, description exacte Répond trop vite aux questions qu'on ne lui a pas posées., Archives du Nexus. Bouton Fermer et fond touchable ferment. Aucune faction, PV, statistiques, secret MJ, notes d'interprétation ni commande contacter. Onglet PNJ actif. État vide : Aucun sujet identifié / En attente de transmission par le MJ.`,
  lieux: `Écran Lieux. Source HubAtlas.tsx + HubAtlasViewer.tsx. Horloge 23:36:58. Titre Atlas des Lieux Visités ; Cartographie des territoires explorés par le groupe. ; compteur 1 Lieux Découverts. Un seul lieu touchable Station Varn, badge battlemap, description Le pont C, entre le sas et le relais. Illustration de plan EXISTANTE dans e2e/donnees/plan-station-varn.png : rectangle avec SAS gauche, QUARTIERS et INFIRMERIE au centre, REGISTRE et SOUTE à droite, RELAIS tout à droite, couloir en croix. L'API ne reçoit pas l'image : prévoir un simple emplacement neutre nommé Plan de Station Varn à remplacer localement par le PNG exact ; NE PAS générer d'autre plan ou illustration. Toucher ouvre la surcouche : ce même plan, Lieu Visité, battlemap, Station Varn, Exploration Documentée, Le pont C, entre le sas et le relais., Atlas du Nexus. Bouton Fermer et fond touchable ferment. Aucune commande zoom, déplacement, itinéraire ou token. Onglet Lieux actif. État vide : Territoires inconnus / Aucun lieu n'a encore été marqué comme visité par le Maître de Jeu.`,
  messages: `Écran Messagerie en SURCOUCHE de Direct, pas un nouvel onglet. Source HubMessenger.tsx. Horloge 23:37:32. Fond Direct : Le Silence de Varn, projection libre, Chroniques de séance / Aucun résumé public. Panneau lisible à 360 px, fermeture Fermer la messagerie ≥44. Titre Messagerie, Canal Direct MJ ; bouton Choisir le destinataire / À : Maître du Jeu ouvre la liste de quatre choix exacts Maître du Jeu, Tous les Joueurs, Idris Koa, Sora Adebayo. Silhouettes neutres, aucun portrait inventé. Pas de filtre de connexion pour ces destinataires. Changer destinataire filtre la conversation et le libellé du canal (Général ou Privé). Au repos uniquement deux messages de démonstration : VOUS 23:37 / Le relais est ouvert. ; MAÎTRE DU JEU 23:37 / Vous entendez trois coups. Champ textarea Entrer un message / Message à Maître du Jeu... ; bouton Envoyer le message ≥44, désactivé si vide ou espaces, Enter envoie, Shift+Enter saut de ligne. Envoi local simulé ajoute uniquement le texte saisi et vide le champ ; n'invente pas de réponse. Avertissement Seul Maître du Jeu pourra lire ce message. ; variante groupe Tout le monde pourra lire ce message. ; autre PJ Seul [nom] pourra lire ce message. Pas de pièces jointes, appels, suppression, recherche, accusés de lecture ou état en ligne. Fermeture révèle Direct ; pied reste intact avec Messages actif tant que ouvert.`,
  notifications: `Écran Notifications, SURCOUCHE de Direct, pas un centre/historique ni nouvel onglet. Source TabletHub.tsx MessageToast et HubNotificationCenter.tsx. Horloge 23:38:05. Fond Direct : Le Silence de Varn, projection libre, Chroniques de séance / Aucun résumé public. État T0 reçu : seule notification touchable Nouveau Message / Maître du Jeu (Maître du Jeu), au-dessus du pied, pas de contenu de message dévoilé dans cette carte. Badge non lu 1 sur Messages, qui ne masque pas son label. Toucher Nouveau Message ouvre la messagerie Canal Direct MJ avec le message reçu Le sas vient de se fermer., destinataire Maître du Jeu, champ Envoyer et fermeture réels comme HubMessenger ; badge lu disparaît. N'ajoute PAS de bouton Tout marquer lu, historique, menu cloche ou diagnostic. Les alertes du HubNotificationCenter sont un AUTRE état conditionnel, pas affiché en même temps dans ce décor : reçu de, titre, texte Markdown, bouton Fermer ≥44, fermeture automatique après 8 secondes. Ne pas les confondre avec la carte Nouveau Message. Boutons et lecture ≥44/14 px.`
};
for (const [nom, contenu] of Object.entries(contenus)) {
  await writeFile(new URL(`${nom}-telephone-requete.json`, dossier), JSON.stringify({ ...exemple, prompt: commun + contenu + " C'est TOUT. N'ajoute rien." }, null, 2));
}
let md = '# T3 — prompts du lot joueurs J2, 2026-10-05\n\nDavid : « on fait J2 ». Archives, PNJ, Lieux, notifications et messagerie.\nLes propositions se consultent dans [la galerie T3](tablettes/T3-propositions/index.html).\nAucun T4 commencé. Les références T0 ont été lues puis transcrites, pas jointes à Stitch.\nToutes les données proviennent du décor fictif des guides.\n\n';
for (const nom of Object.keys(contenus)) md += `## ${nom} — téléphone\n\n\`\`\`text\n${commun}${contenus[nom]} C'est TOUT. N'ajoute rien.\n\`\`\`\n\n`;
await writeFile(new URL('../../2026-10-05-prompts-stitch-tablettes-J2.md', dossier), md);
