import {readFile,writeFile} from 'node:fs/promises';
const dossier=new URL('.',import.meta.url);
const ecrans=[
 ['pads','M1.1','Pads','01-pads','Volumes Musique et Ambiances, filtrage des pads, choix de sortie et projection du plan du relais.',[['ambiance','Ambiance active'],['sortie','Sortie audio'],['filtre','Filtre sans résultat'],['vide','Sans pads'],['non-appairee','Sans appairage'],['reconnexion','Reconnexion'],['statut','Ambiance et minuteur']]],
 ['des','M1.2','Dés','02-des','Sept dés, trois compteurs, onze modes et choix du pilote. Le résultat est une illustration fixe, sans moteur de dés.',[['modes','Onze modes'],['formule','Formule libre'],['resultat','Résultat de démonstration'],['echelonne','Pilote échelonné']]],
 ['combat','M1.3','Combat','06-combat','Ordre d’initiative, round, Suivant et ajustement des PV. Idris conserve sa jauge absente ; les ennemis sont masqués en aventure.',[['suivant','Tour suivant'],['aventure','Mode aventure'],['vide','Sans combat']]],
 ['sons','M2.1','Sons','04-sons','Volume des bruitages et Alarme du relais. Une seule entrée : aucun filtre ajouté.',[['sortie','Sortie audio'],['vide','Sans bruitage']]],
 ['scenario','M2.2','Scénario','05-scenario','Deux moments ordonnés du storyboard. Le toucher simule leur déclenchement.',[['moment','Moment choisi'],['vide','Sans storyboard']]],
 ['tableau','M2.3','Tableau','07-tableau','Crayon, gomme, formes, laser, épaisseurs, huit couleurs, fond clair ou sombre, annulation et effacement.',[['clair','Fond clair'],['dessin','Rectangle tracé']]],
 ['notes','M2.4','Notes','09-notes-seance','Les six vues : Séance, Trame, Chroniques, Nexus Wiki, Indices et Secrets. Lecture seule, avec pliage et recherche.',[['scene','Scène ouverte'],['trame','Trame'],['chroniques','Chroniques filtrées'],['indices','Indices'],['secrets','Secrets fictifs MJ'],['coffre','Nexus Wiki'],['note','Note Markdown'],['note-tableau','Tableau Markdown'],['aventure','Secrets masqués']]],
 ['messages','M2.5','Messages','15-messages','Tous montre toutes les conversations et envoie à tous. Les conversations privées suivent le destinataire choisi.',[['prive','Message privé'],['envoyes','Toutes les conversations'],['recu','Message reçu']]],
];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const manifest=[];
for(const [nom,lot,titre] of ecrans)for(const format of ['telephone','paysage']){
 const brut=JSON.parse(await readFile(new URL(`${nom}-${format}-reponse.json`,dossier),'utf8'));
 const rep=brut.result;
 const session=rep.outputComponents?rep:JSON.parse(rep.content.find(c=>c.text)?.text);
 const screen=session.outputComponents.flatMap(c=>c.design?.screens||[])[0];
 manifest.push({lot,titre,format,projet:session.projectId,session:session.sessionId,id:screen.id,nom:screen.name,largeurStitch:screen.width,hauteurStitch:screen.height,export:`${nom}-${format}-original.html`,proposition:`${nom}-${format}.html`,requete:`${nom}-${format}-requete.json`,reponse:`${nom}-${format}-reponse.json`});
}
await writeFile(new URL('ecrans.json',dossier),JSON.stringify(manifest,null,2));
const liens=ecrans.map(([nom,,titre])=>`<a href="#${nom}">${titre}</a>`).join('');
const sections=ecrans.map(([nom,lot,titre,t0,description,variantes])=>`<section id="${nom}"><h2>${lot} — ${titre} · Retenu</h2><p>${description}</p><div class="rendus"><figure class="mobile"><figcaption>Téléphone</figcaption><a data-image="${nom}/telephone" href="rendus/${nom}-telephone-390.png"><img data-ecran="${nom}" data-format="telephone" src="rendus/${nom}-telephone-390.png" alt="${titre}, proposition téléphone"></a></figure><figure><figcaption>iPad Air paysage</figcaption><a data-image="${nom}/paysage" href="rendus/${nom}-paysage-1180.png"><img data-ecran="${nom}" data-format="paysage" src="rendus/${nom}-paysage-1180.png" alt="${titre}, proposition paysage"></a></figure></div><div class="liens"><a href="${nom}-telephone.html">Prototype téléphone</a><a href="${nom}-paysage.html">Prototype paysage</a><a href="rendus/${nom}-telephone-820.png">iPad portrait</a><a href="rendus/${nom}-paysage-1440.png">Pupitre</a></div><details><summary>États et gestes vérifiés</summary><div class="liens">${variantes.map(([etat,label])=>`<a href="rendus/${nom}-telephone-360-${etat}.png">${label} · 360 px</a><a href="rendus/${nom}-paysage-1180-${etat}.png">${label} · paysage</a>`).join('')}</div></details><details><summary>Exports Stitch bruts et provenance</summary><p>Les exports bruts comportent des ajouts corrigés dans les propositions. Les messages de Stitch ne constituent pas une validation.</p><div class="liens">${['telephone','paysage'].map(format=>`<a href="${nom}-${format}-original.html">HTML brut · ${format}</a><a href="rendus/${nom}-${format}-original.png">Rendu brut · ${format}</a><a href="${nom}-${format}-requete.json">Requête · ${format}</a><a href="${nom}-${format}-reponse.json">Réponse et suggestions · ${format}</a>`).join('')}</div></details></section>`).join('\n');
await writeFile(new URL('index.html',dossier),`<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>T3 — propositions meneur M1 et M2</title><style>
:root{color-scheme:dark;font:16px/1.6 system-ui,sans-serif;color:#f8fafc;background:#020617}*{box-sizing:border-box}body{margin:0}main{max-width:1500px;margin:auto;padding:32px}h1{font-size:clamp(26px,4vw,40px);margin:8px 0}h2{font-size:24px;margin-bottom:4px}p{max-width:900px;color:#b9c3d4}a{color:#67e8f9;overflow-wrap:anywhere}a:focus-visible,button:focus-visible,select:focus-visible,summary:focus-visible{outline:2px solid #67e8f9;outline-offset:4px}.repere{color:#67e8f9;font-size:13px;letter-spacing:.12em;text-transform:uppercase}.commandes{display:flex;flex-wrap:wrap;align-items:center;gap:16px;margin:24px 0;padding:16px;background:#0f172a;border:1px solid #334155}select,button{min-height:44px;padding:10px 16px;background:#1e293b;color:#f8fafc;border:1px solid #64748b;font:inherit;cursor:pointer}button[aria-pressed=true]{background:#06b6d4;color:#020617;border-color:#06b6d4}section{margin-top:32px;border-top:1px solid #334155;padding-top:16px}.rendus{display:grid;grid-template-columns:minmax(200px,390px) minmax(0,1fr);gap:24px;align-items:start}figure{margin:0;min-width:0}figcaption{margin-bottom:10px;color:#cbd5e1}img{display:block;width:100%;height:auto;border:1px solid #334155}.liens{display:flex;gap:16px;flex-wrap:wrap;padding:12px 0}details{margin:16px 0;padding:16px;background:#0f172a}summary{cursor:pointer;min-height:44px}@media(max-width:800px){main{padding:16px}.rendus{grid-template-columns:1fr}.mobile{max-width:390px}}
</style></head><body><main><div class="repere">GM-OS · T3 · 06 octobre 2026 · Lots M1 et M2</div><h1>Propositions du meneur</h1><p>Les huit onglets de la télécommande, en téléphone et iPad paysage, avec vérification du portrait et du pupitre. Les huit écrans sont retenus après ton accord du 06/10. T3 est terminé. Les boutons des prototypes simulent les gestes avec la campagne fictive « Le Silence de Varn ».</p><p>Les versions locales reconstruisent les panneaux issus de Stitch avec les commandes et les données du relevé T0. Les résultats de dés illustrent l’affichage. Ces maquettes ne valident pas la synchronisation ni Safari sur iPad.</p><div class="liens"><a href="../T3-propositions/index.html">Propositions joueurs J1 et J2</a><a href="README.md">Relevé et limites</a><a href="controles.json">Contrôles des 40 formats</a></div><nav class="liens" aria-label="Les huit propositions">${liens}</nav><div class="commandes"><span>Vue :</span><button id="propositions" aria-pressed="true">Propositions T3</button><button id="references" aria-pressed="false">Références T0</button><label for="largeur">Téléphone :</label><select id="largeur"><option value="390">390 × 844</option><option value="360">360 × 800</option></select><span id="precision" role="status">iPad paysage : 1180 × 820.</span></div><p>La ligne d’état et « Couper le son » sont communs aux huit écrans. Maintenir 700 ms coupe le son ; relâcher avant annule. Le résultat de dés disparaît après quinze secondes ou en touchant le fond extérieur. Le libellé « CLIQUER POUR FERMER » reste inopérant, comme dans le T0.</p>${sections}</main><script>
const numeros=${JSON.stringify(Object.fromEntries(ecrans.map(([nom,,,t0])=>[nom,t0])))};
let avant=false;
function afficher(){const largeur=document.getElementById('largeur').value;for(const img of document.querySelectorAll('img[data-ecran]')){const {ecran,format}=img.dataset;const src=avant?'../T0-meneur/'+format+'/'+numeros[ecran]+'.png':'rendus/'+ecran+'-'+format+'-'+(format==='telephone'?largeur:'1180')+'.png';img.src=src;img.parentElement.href=src;img.alt=(avant?'Référence T0':'Proposition T3')+' '+ecran+' '+format;}document.getElementById('propositions').setAttribute('aria-pressed',String(!avant));document.getElementById('references').setAttribute('aria-pressed',String(avant));document.getElementById('precision').textContent=avant?'T0 : téléphone 390 × 844 et paysage 1180 × 820.':'iPad paysage : 1180 × 820.';}
document.getElementById('propositions').onclick=()=>{avant=false;afficher();};document.getElementById('references').onclick=()=>{avant=true;afficher();};document.getElementById('largeur').onchange=afficher;
</script></body></html>`);
console.log('Galerie M1/M2 et manifeste des 16 exports produits.');
