import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
const dossier=new URL('.',import.meta.url);
const session=JSON.parse(await readFile(new URL('../../../../e2e/donnees/campagne-de-demo.json',dossier),'utf8')).modules.sessionOS;
const commun="DÉCOR ENTIÈREMENT FICTIF du banc e2e/tabletteMeneurT0.spec.ts et e2e/donnees/campagne-de-demo.json ; aucun profil réel ni donnée personnelle. GM-OS T3, nouvelle conversation pour cet écran de TÉLÉCOMMANDE DU MENEUR, 390×844, utilisable à360px. Même DESIGN.md que les joueurs : #020617, panneaux #0f172a/#1e293b, texte #f8fafc, secondaire #898c95, cyan #06b6d4, danger #ef4444 ; Orbitron titres, Inter lecture≥14, JetBrains Mono chiffres, badges≥11. Cibles et curseurs≥44×44, zoom autorisé. AUCUN bandeau de bureau, menu27modules, réglage de thème ou mode performance joueur. Ligne d’état permanente : voyant connecté appairé, R1 · Nel Varga, Couper le son (maintenir700ms, progression visible, relâcher annule). Musique, ambiance, minuteur, non-lus seulement si actifs, jamais de faux tirets. Huit onglets complets en pied sur deux rangées de4 : Pads, Dés, Sons, Scénario, Combat, Tableau, Notes, Messages. Contenu défilant AU-DESSUS du pied. HTML gestes simulés localement ; aucune écriture/réseau de campagne. Captures T0 lues et transcrites, pas jointes à l’API. ";
const contenus={
 pads:"M1 Pads, source RemoteUniversalPads/LigneDeVolume. Réglages Musique et Ambiances, chacun volume100%, curseur, Sortie par défaut ; menu cette seule sortie et Aucune autre sortie recensée sur la machine du meneur. Filtrer les pads… +effacement, sans accents. Aucun pad musique. Ambiances : Arcologie/Cyberpunk, Club Néon/Cyberpunk, Forêt Enchantée/Fantastique. Images : Plan du relais, emplacement neutre à remplacer par PNG exact e2e/donnees/plan-station-varn.png. Toucher déclenche, actif cyan. Plafonds5/8/12 signalés seulement si tronqués, absent ici. Réglages restent si vide : Aucun pad configuré sur cet univers. Aucun upload/édition.",
 des:"M1 Dés, RemoteDicePad/RemoteDiceResultOverlay. T0 sans pilote configuré : Quantité / Base1 ±borné1..99 ; Modificateur0 ± ; Seuil (Target)10 ±0..99. Mode de Lancer Standard d20/d6 ; menu11modes : Standard d20/d6, Somme Explosive, Formule Libre, Jet de Seuil (Target), Pool de Dés (Succès), Pool Explosif, Avantage (Garde Meilleur), Désavantage (Garde Pire), Year Zero Engine, FATE / Fudge, Rolemaster. D4 D6 D8 D10 D12 D20 D100 et Réinitialiser. Manuel indique Manuel ; retour Réinitialiser au système. Formule Libre remplace réglages par input ex:2d10+1d4+5 et Lancer la formule personnalisée. Résultat conditionnel DÉTAIL DU JET, total/valeurs/verdict si présent, toucher FOND ferme, expire15s. Libellé actuel Cliquer pour fermer inopérant dans panneau : ne pas réparer implicitement, maquette non intégrée. Aucun historique ajouté.",
 combat:"M1 Combat, RemoteCombatTracker. Round1, Suivant. Trois combattants EXACTS T0 : initiative17 Nel Varga Joueur PV9 ; initiative12 L’Écho Ennemi PV18 ; initiative0 Idris Koa Joueur PV vide (absent dans capture). Nel actif. Cartes ±PV44px, noms entiers. Suivant change actif puis round après dernier. Aventure conditionnel ennemi Caché sans PV/±. Aucun ajout, attaque, statut ou modèle de santé inventé, modèles absents ici. Vide Aucun combat en cours.",
 sons:"M2 Sons, RemoteSoundboard. Volume — Bruitages100%, curseur, Sortie par défaut/menu même sortie ; seul pad Alarme du relais avec icône neutre, toucher déclenche sans son réel. Filtre uniquement si >8 : absent ici. Aucun fichier inventé. Vide Aucun bruitage dans l’ambiance active. Arrêt général dans ligne d’état uniquement.",
 scenario:"M2 Scénario, RemoteStoryboard. Deux boutons ordonnés numérotés : 01 Amarrage au relais ; 02 La voix dans le relais. Toucher déclenche. Seulement numéro, nom, icône lecture ; aucune description, édition ou nouvelle étape. Vide Aucun moment dans le storyboard de cette campagne.",
 tableau:"M2 Tableau, RemoteWhiteboardView. Surface dessin T0 avec rectangle cyan x15..55%,y20..70%. Crayon actif, Gomme, Laser, Rectangle, Cercle ; traits Fin2 Moyen4 Épais8 ; fond clair/sombre, Annuler, Rétablir, Effacer tout sans confirmation ajoutée. Huit couleurs blanc/noir selon fond, rouge, bleu, vert, ambre, violet, rose, cyan. Outils/couleurs≥44, rangées à360, aucun contrôle hors cadre. Surface prend place restante ; doigt trace, gomme retire, laser temporaire. Aucun calque/export/import/zoom/sauvegarde.",
 notes:"M2 Notes, RemoteNotes/RemoteObsidian. Six vues accessibles Séance, Trame3, Chroniques3, Nexus Wiki, Indices4, Secrets. Séance : Ce qui se joue1 Entretien avec Hale (acte Ce que Hale n’a pas dit) ; En pause0 Rien ici ; À jouer4 La voix dans le relais, Le registre réécrit, Descente vers le noyau, Confrontation avec l’Écho ; Résumé public Le relais demeure silencieux. Scène déplie résumé. Trame3actes : L’arrivee achevé/Amarrage Close ; Ce que Hale n’a pas dit/les3scènes ; Ce qui écoute/les2dernières ; repli acte/scène. Chroniques recherche3fiches Station Varn, Ancre-7, Protocole de quarantaine, catégories, détail Markdown. Indices4 badges Donné/En main textes exacts semence, aucune action révéler. Secrets fictif Hale connaît la panne. Aventure protège. Nexus Wiki recherche/recharger/dossiers PNJ Lieux Séances +Station Varn ; ouvrir note Markdown/Retour à la liste. Aucun créer/modifier/supprimer/IA. Texte absent : emplacement neutre, remplacement local depuis semence exacte.",
 messages:"M2 Messages, RemoteMessenger. Initial Tous ; correspondants ordre alphabétique Idris Koa, Nel Varga, Sora Adebayo. Fil vide Rien dans ce fil. INPUT Message à envoyer, Écrire à Tous les joueurs…, Envoyer le message≥44, désactivé vide/espaces ; Enter envoie texte saisi/vide champ, aucune réponse automatique. Tous affiche TOUT le fil général ET privé, mais envoie au groupe ; un PJ filtre messages entrants/sortants du personnage, placeholder Écrire à [nom]… ; pas le filtre joueur J2. Envois MJ àdroite méta →Tous/nom/heure. Correspondants ayant écrit restent hors ligne. Aucun statut en ligne/pièce jointe/appel/accusé/suppression ni préremplissage absent du T0."
};
const reference=JSON.parse(await readFile(new URL('../T3-propositions/cartes-telephone-requete.json',dossier),'utf8'));
let md='# T3 — prompts M1 et M2, 2026-10-05\n\nDavid : « fait M1 et M2 ». Maquettes meneur, aucune intégration T4.\nCaptures T0 transcrites, pas jointes ; décor fictif uniquement.\n\n';
for(const [nom,contenu] of Object.entries(contenus)){
 const prompt=commun+contenu+" C’est TOUT. N’ajoute rien.";
 await writeFile(new URL(`${nom}-telephone-requete.json`,dossier),JSON.stringify({projectId:reference.projectId,deviceType:'MOBILE',designSystem:reference.designSystem,prompt},null,2));
 md+=`## ${nom} — téléphone\n\n\`\`\`text\n${prompt}\n\`\`\`\n\n`;
}
await writeFile(new URL('../../2026-10-05-prompts-stitch-tablettes-M1-M2.md',dossier),md);
const coffre=[];async function parcourir(url,chemin=''){for(const e of await readdir(url,{withFileTypes:true})){const relatif=chemin+e.name;if(e.isDirectory())await parcourir(new URL(e.name+'/',url),relatif+'/');else if(e.name.endsWith('.md'))coffre.push({chemin:relatif,contenu:await readFile(new URL(e.name,url),'utf8')});}}
await parcourir(new URL('../../../../e2e/donnees/coffre-de-demo/',dossier));
await writeFile(new URL('donnees-demo.json',dossier),JSON.stringify({actes:session.actes,scenes:session.scenes,wiki:session.wikiEntries,indices:session.clues,coffre},null,2));
await mkdir(new URL('assets/',dossier),{recursive:true});await writeFile(new URL('assets/plan-station-varn.png',dossier),await readFile(new URL('../../../../e2e/donnees/plan-station-varn.png',dossier)));
