import {chromium,expect} from '@playwright/test';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const dossier=new URL('.',import.meta.url);await mkdir(new URL('rendus/',dossier),{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const ecrans=process.argv.slice(2).length?process.argv.slice(2):['pads','des','combat','sons','scenario','tableau','notes','messages'];
const controles=[];
const verifier=async(page,etape)=>{
 const mesures=await page.evaluate(()=>({largeur:innerWidth,largeurPage:document.documentElement.scrollWidth,petitesCibles:[...document.querySelectorAll('button,a[role=button],input,select,summary')].map(n=>{const r=n.getBoundingClientRect();return{nom:n.getAttribute('aria-label')||n.innerText||n.id,largeur:r.width,hauteur:r.height};}).filter(r=>r.largeur>0&&r.hauteur>0&&(r.largeur<43.9||r.hauteur<43.9))}));
 if(mesures.largeurPage>mesures.largeur||mesures.petitesCibles.length)throw new Error(`${etape}: ${JSON.stringify(mesures)}`);return mesures;
};
try{for(const nom of ecrans)for(const format of ['telephone','paysage'])for(const [largeur,hauteur] of format==='telephone'?[[390,844],[360,800],[820,1180]]:[[1180,820],[1440,900]]){
 const page=await browser.newPage({viewport:{width:largeur,height:hauteur},deviceScaleFactor:1});const erreurs=[],echecs=[];
 page.on('pageerror',e=>erreurs.push(e.message));page.on('requestfailed',r=>echecs.push(r.url()));await page.clock.install();await page.clock.pauseAt(new Date());
 const cle=`${nom}-${format}-${largeur}`,url=new URL(nom+'-'+format+'.html',dossier).href;
 const ouvrir=async(etat='')=>{await page.goto(url+(etat?'?etat='+etat:''),{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);};
 const capture=async(etat='')=>{await verifier(page,cle+'/'+etat);await page.screenshot({path:fileURLToPath(new URL('rendus/'+cle+(etat?'-'+etat:'')+'.png',dossier))});};
 const cliquer=nom=>page.getByRole('button',{name:nom,exact:true}).click();
 await ouvrir();const base=await verifier(page,cle);await capture();const navigation=await page.locator('#navigation a').allTextContents();
 expect(navigation).toEqual(['Pads','Dés','Sons','Scénario','Combat','Tableau','Notes','Messages']);
 for(const a of await page.locator('#navigation a').all()){const r=await a.boundingBox();if(!r||r.x<0||r.x+r.width>largeur+1||r.y+r.height>hauteur+1)throw new Error(`${cle}: navigation masquée`);}
 const appuyer=async duree=>{const r=await page.locator('#couper').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.clock.runFor(duree);await page.mouse.up();};
 await appuyer(300);expect(await page.locator('body').getAttribute('data-arret-audio')).toBeNull();await appuyer(720);expect(await page.locator('body').getAttribute('data-arret-audio')).toBe('true');
 const gestes={navigation:true,appuiCourtAnnule:true,appuiLong700ms:true};
 if(nom==='pads'||nom==='sons'){
  const voie=nom==='pads'?'Musique':'Bruitages';const slider=page.getByRole('slider',{name:'Volume — '+voie,exact:true});await slider.focus();await page.keyboard.press('Home');await expect(page.locator(`[data-volume-sortie="${voie}"]`)).toHaveText('0%');
  await cliquer('Sortie — '+voie);await expect(page.getByRole('menu')).toBeVisible();await verifier(page,cle+'/sortie');await capture('sortie');await page.getByRole('menuitem',{name:'Sortie par défaut'}).click();await expect(page.getByRole('menu')).toBeHidden();
  if(nom==='pads'){
   await page.getByRole('searchbox',{name:'Filtrer les pads'}).fill('foret');await expect(page.getByRole('button',{name:/Forêt Enchantée/})).toBeVisible();await expect(page.getByRole('button',{name:/Arcologie/})).toBeHidden();await cliquer('Effacer le filtre');
   await page.getByRole('button',{name:/Arcologie/}).click();await expect(page.locator('#ambiance-statut')).toHaveText('Arcologie');await capture('ambiance');
   await page.getByRole('button',{name:/Plan du relais/}).click();expect(await page.locator('body').getAttribute('data-projection')).toBe('true');
   const image=await page.locator('img').evaluate(i=>({src:i.getAttribute('src'),chargee:i.complete&&i.naturalWidth>0}));expect(image).toEqual({src:'assets/plan-station-varn.png',chargee:true});
   await appuyer(720);await expect(page.getByRole('button',{name:/Plan du relais/})).toHaveClass(/actif/);expect(await page.locator('body').getAttribute('data-projection')).toBe('true');await expect(page.locator('#ambiance-statut')).toHaveCount(0);
   await page.getByRole('searchbox',{name:'Filtrer les pads'}).fill('absent');await expect(page.locator('#rien-pads')).toBeVisible();await capture('filtre');
  }else {await cliquer('Alarme du relais');expect(await page.locator('body').getAttribute('data-bruitage')).toBe('true');expect(await page.getByRole('searchbox').count()).toBe(0);}
  await ouvrir('vide');await expect(page.getByRole('slider',{name:'Volume — '+voie})).toBeVisible();await capture('vide');Object.assign(gestes,{volume:true,sortie:true,pads:true,vide:true});
 }else if(nom==='des'){
  await cliquer('Augmenter la quantité');await expect(page.locator('#quantite')).toHaveText('2');await cliquer('Augmenter le modificateur');await expect(page.locator('#modificateur')).toHaveText('1');await cliquer('Augmenter le seuil');await cliquer('Réinitialiser les dés');await expect(page.locator('#quantite')).toHaveText('1');await expect(page.locator('#seuil')).toHaveText('10');
  await cliquer('Standard d20/d6');expect(await page.locator('#modes button').count()).toBe(11);await capture('modes');await cliquer('Formule Libre');await expect(page.getByRole('button',{name:'Lancer la formule personnalisée'})).toBeDisabled();await page.getByRole('textbox',{name:'Formule de dés'}).fill('2d10+1d4+5');await capture('formule');await cliquer('Lancer la formule personnalisée');await capture('resultat');
  await page.getByText('CLIQUER POUR FERMER',{exact:true}).click();await expect(page.locator('#jet')).toBeVisible();await page.mouse.click(4,4);await expect(page.locator('#jet')).toBeHidden();
  await ouvrir();await cliquer('Lancer D20');await page.clock.runFor(14900);await expect(page.locator('#jet')).toBeVisible();await page.clock.runFor(100);await expect(page.locator('#jet')).toBeHidden();
  await ouvrir('pilote');await cliquer('Lancer Système');await expect(page.locator('#jet')).toBeVisible();await page.mouse.click(4,4);
  await ouvrir('echelonne');await expect(page.getByLabel('Attribut',{exact:true})).toBeVisible();await cliquer('Avantage');await expect(page.locator('#poignee')).toHaveText('D10 + D8 + D8');await page.getByLabel('Équip.',{exact:true}).selectOption('D');await capture('echelonne');Object.assign(gestes,{compteurs:true,modes11:true,formule:true,pilote:true,echelonne:true,resultat:true,fermetureFond:true,libelleInoperantConserve:true,expiration15s:true});
 }else if(nom==='combat'){
  await cliquer('Retirer un point de vie à Nel Varga');await expect(page.locator('[data-pv="0"]')).toHaveText('8');await cliquer('Ajouter un point de vie à Nel Varga');await expect(page.locator('[data-pv="0"]')).toHaveText('9');await cliquer('Ajouter un point de vie à Idris Koa');await expect(page.locator('[data-pv="2"]')).toHaveText('');
  await cliquer('Suivant');await expect(page.locator('#tour-statut')).toHaveText('R1 · L’Écho');await capture('suivant');await cliquer('Suivant');await cliquer('Suivant');await expect(page.locator('#round')).toHaveText('2');
  await ouvrir('aventure');await expect(page.locator('[data-combattant="1"]')).toContainText('Caché');expect(await page.locator('[data-combattant="1"] button').count()).toBe(0);await capture('aventure');await ouvrir('vide');await capture('vide');Object.assign(gestes,{pv:true,sansJauge:true,suivant:true,round:true,aventure:true,vide:true});
 }else if(nom==='scenario'){
  await page.getByRole('button',{name:/01 Amarrage au relais/}).click();expect(await page.locator('body').getAttribute('data-moment')).toBe('0');await page.getByRole('button',{name:/02 La voix dans le relais/}).click();expect(await page.locator('body').getAttribute('data-moment')).toBe('1');await capture('moment');await ouvrir('vide');await capture('vide');Object.assign(gestes,{moments:true,vide:true});
 }else if(nom==='tableau'){
  await cliquer('Passer en fond clair');await expect(page.locator('.surface-dessin')).toHaveClass(/clair/);await capture('clair');await cliquer('Gomme');await expect(page.locator('#dessin')).toHaveAttribute('data-outil','eraser');await cliquer('Trait épais');await cliquer('Choisir la couleur #ef4444');await expect(page.locator('#dessin')).toHaveAttribute('data-epaisseur','8');await expect(page.locator('#dessin')).toHaveAttribute('data-couleur','#ef4444');
  await cliquer('Rectangle');await page.locator('#dessin').scrollIntoViewIfNeeded();const r=await page.locator('#dessin').boundingBox();await page.mouse.move(r.x+r.width*.6,r.y+r.height*.3);await page.mouse.down();await page.mouse.move(r.x+r.width*.85,r.y+r.height*.6,{steps:5});await page.mouse.up();await expect(page.locator('#dessin')).toHaveAttribute('data-traces','2');await capture('dessin');
  await cliquer('Annuler');await expect(page.locator('#dessin')).toHaveAttribute('data-traces','1');await cliquer('Rétablir');await expect(page.locator('#dessin')).toHaveAttribute('data-traces','2');await cliquer('Laser');await page.locator('#dessin').scrollIntoViewIfNeeded();await page.mouse.move(r.x+r.width*.5,r.y+r.height*.5);await page.mouse.down();await page.mouse.up();await expect(page.locator('#dessin')).toHaveAttribute('data-traces','2');await cliquer('Effacer tout');await expect(page.locator('#dessin')).toHaveAttribute('data-traces','0');Object.assign(gestes,{outils:true,couleurs:true,epaisseur:true,fond:true,dessin:true,annuler:true,retablir:true,laserTemporaire:true,effacer:true});
 }else if(nom==='notes'){
  await page.locator('[data-scene="temoin-scene-2"] summary').click();await expect(page.getByText('Il repond a tout, et trop vite.',{exact:true})).toBeVisible();await capture('scene');await cliquer('Trame 3');expect(await page.locator('[data-acte]').count()).toBe(3);await page.locator('[data-acte="temoin-acte-2"]>summary').click();await expect(page.locator('[data-acte="temoin-acte-2"]')).not.toHaveAttribute('open','');await capture('trame');
  await cliquer('Chroniques 3');await page.getByRole('searchbox',{name:'Chercher dans le wiki'}).fill('quarantaine');await page.locator('#resultats-wiki summary').click();await expect(page.getByText('Scelle les ponts inférieurs au moindre signal non identifié.',{exact:true})).toBeVisible();await capture('chroniques');await cliquer('Effacer la recherche');expect(await page.locator('#resultats-wiki details').count()).toBe(3);
  await cliquer('Indices 4');await capture('indices');await expect(page.getByText('La pièce manquante',{exact:true})).toBeVisible();await cliquer('Secrets');await expect(page.getByText('Hale connaît la panne.',{exact:true})).toBeVisible();await capture('secrets');
  await cliquer('Nexus Wiki');await capture('coffre');await page.getByRole('searchbox',{name:'Chercher une note dans le coffre'}).fill('hale');await page.getByRole('button',{name:'PNJ/Superviseur Hale',exact:true}).click();await expect(page.locator('.markdown h1')).toHaveText('Superviseur Hale');await capture('note');await cliquer('Revenir à la liste');await page.getByRole('searchbox',{name:'Chercher une note dans le coffre'}).fill('');await cliquer('▣ PNJ');await expect(page.getByRole('button',{name:'Superviseur Hale',exact:true})).toBeVisible();await cliquer('Coffre');await cliquer('Station Varn');await expect(page.locator('.markdown table')).toBeVisible();await capture('note-tableau');await cliquer('Revenir à la liste');await cliquer('Recharger le coffre');expect(await page.locator('body').getAttribute('data-coffre-recharge')).toBe('true');
  await ouvrir('aventure');await cliquer('Secrets');await expect(page.getByText('Hale connaît la panne.',{exact:true})).toHaveCount(0);await capture('aventure');Object.assign(gestes,{vues6:true,scene:true,trame:true,chroniques:true,indices:true,secrets:true,coffre:true,markdown:true,dossiers:true,recharger:true,aventure:true});
 }else if(nom==='messages'){
  await expect(page.getByRole('button',{name:'Envoyer le message'})).toBeDisabled();await page.getByRole('textbox',{name:'Message à envoyer'}).fill('   ');await expect(page.getByRole('button',{name:'Envoyer le message'})).toBeDisabled();await page.getByRole('textbox',{name:'Message à envoyer'}).fill('Le sas est ouvert.');await cliquer('Envoyer le message');await expect(page.getByText('Le sas est ouvert.',{exact:true})).toBeVisible();await cliquer('Nel Varga');await expect(page.getByText('Le sas est ouvert.',{exact:true})).toHaveCount(0);await page.getByRole('textbox',{name:'Message à envoyer'}).fill('Reste près du relais.');await page.getByRole('textbox',{name:'Message à envoyer'}).press('Enter');await expect(page.getByRole('textbox',{name:'Message à envoyer'})).toHaveValue('');await capture('prive');await cliquer('Tous');await expect(page.getByText('Reste près du relais.',{exact:true})).toBeVisible();await expect(page.getByText('Le sas est ouvert.',{exact:true})).toBeVisible();await capture('envoyes');await cliquer('Idris Koa');await expect(page.getByText('Reste près du relais.',{exact:true})).toHaveCount(0);await page.getByRole('textbox',{name:'Message à envoyer'}).fill('<texte>');await cliquer('Envoyer le message');await expect(page.getByText('<texte>',{exact:true})).toBeVisible();await ouvrir('recu');await expect(page.getByText('Le relais est ouvert.',{exact:true})).toBeVisible();await capture('recu');Object.assign(gestes,{videDesactive:true,envoi:true,enter:true,prive:true,tousMontreTout:true,texteEchappe:true,nonLu:true});
 }
 if(nom==='pads'){
  await ouvrir('non-appairee');await expect(page.getByText('Non appairée',{exact:true})).toBeVisible();await capture('non-appairee');await ouvrir('reconnexion');await capture('reconnexion');await ouvrir('statut');await expect(page.locator('#ambiance-statut')).toHaveText('Arcologie');await expect(page.locator('#minuteur')).toHaveText('2:00');await capture('statut');await ouvrir('recu');await page.getByRole('button',{name:'1 message non lu'}).click();await expect(page.getByText('Le relais est ouvert.',{exact:true})).toBeVisible();gestes.etatsLiaison=true;
 }
 if(erreurs.length||echecs.length)throw new Error(`${cle}: ${JSON.stringify({erreurs,echecs})}`);
 controles.push({fichier:nom+'-'+format+'.html',largeur,hauteur,erreurs,echecs,...base,gestes});await page.close();console.log(cle+': contrôles et gestes OK');
}}finally{await browser.close();await enregistrer();}
async function enregistrer(){
let precedents=[];try{precedents=JSON.parse(await readFile(new URL('controles.json',dossier),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
const cles=new Set(controles.map(c=>c.fichier+'/'+c.largeur));await writeFile(new URL('controles.json',dossier),JSON.stringify([...precedents.filter(c=>!cles.has(c.fichier+'/'+c.largeur)),...controles],null,2));
}
